CREATE TABLE CUSTOMERSS(ID INT,NAME VARCHAR(100),AGE INT,ADDRESS VARCHAR(100),SALARY INT);
INSERT INTO CUSTOMERSS VALUES (1,'Ramesh',32,'Ahmedabad',2000.00); 
INSERT INTO CUSTOMERSS VALUES (2,'Khilan',25,'Delhi ',1500.00); 
INSERT INTO CUSTOMERSS VALUES (3,'kaushik',23,'Kota ',2000.00); 
INSERT INTO CUSTOMERSS VALUES (4,'Chaitali',25,'Mumbai ',6500.00); 
INSERT INTO CUSTOMERSS VALUES (5,'Hardik',27,'Bhopal',8500.00); 
INSERT INTO CUSTOMERSS VALUES (6,'Komal',22,'MP',4500.00); 
INSERT INTO CUSTOMERSS VALUES (7,'Muffy',24,'Indore',10000.00); 
INSERT INTO CUSTOMERSS VALUES (8,'Mastan',28,'Indore',20000.00);
SELECT * FROM CUSTOMERSS
SELECT SALARY FROM CUSTOMERS GROUP BY SALARY HAVING SALARY>=2000
SELECT * FROM EMPLOYEES1
SELECT 18/8 FROM DUAL
SELECT TO_CHAR(SYSDATE,'DD-MM-YY DAY MONTH YEAR W WW WWW')FROM DUAL;
SELECT TO_CHAR(15,'99V9999') FROM DUAL;
SELECT RPAD(NAME,10,'$')FROM EMPLOYEES1
SELECT LPAD(NAME,10,'$')FROM EMPLOYEES1
SELECT RTRIM('*HELLO','')FROM EMPLOYEES1
SELECT LTRIM('*HELLO','')FROM EMPLOYEES1
SELECT LOWER('HII')FROM EMPLOYEES1
SELECT UPPER('LALITESH')FROM EMPLOYEES1
SELECT UPPER(NAME)FROM EMPLOYEES1
SELECT LOWER(NAME)FROM EMPLOYEES1
SELECT INITCAP(NAME)FROM EMPLOYEES1
SELECT LENGTH('HELLO') FROM DUAL;
SELECT INSTR('HII HELLO','H') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,2) FROM DUAL
SELECT LAST_DAY(SYSDATE) FROM DUAL
SELECT ADD_MONTHS(SYSDATE,2) FROM DUAL
SELECT MONTHS_BETWEEN('08-MAR-2024','08-MAR-2004')FROM DUAL
SELECT GREATEST(900,400,700) FROM DUAL
SELECT TRUNC(SYSDATE,'DD') FROM DUAL
SELECT ROUND(12.52) FROM DUAL